spring.application.name=interview
spring.datasource.url=jdbc:h2:mem:imdbdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.hikari.maximum-pool-size=500
converter.file.path=E:\\sample-data\\
management.endpoints.web.exposure.include=metrics,prometheus
metrics.distribution.slo.http.server.requests=10ms,50ms,100ms,500ms